### ISSUE TITLE
question: shold every page be wrapped by NextTranlationProvider 

### ISSUE THREAD

**Issue by zakidze** [vordgi/next-translation#58]

**Comment by vordgi** [comment]
Yeap, unfortunately this is the only way. Layout does not support updating

**Comment by zakidze** [comment]
is it not possible to use 1 provider in root layout pass all the jsons to it ....and only load the nessiary json per page????

**Comment by vordgi** [comment]
Yeap. But it isn't possible not because package can't pass all jsons to root layout. It isn't possible because it isn't possible to make layout works expectedly - render on each page, with page params, on the top of other components.

It is rendered independently rather than at the top.

That is at assembling time, it's not:

```js
<Layout>
  <Page>
</Layout>
```
at assembling time it is:

```js
//
<Layout />
//
<Page />
```
